services:
    # Proxy
    proxy:
        restart: unless-stopped
        image: jc21/nginx-proxy-manager:latest
        container_name: nginx-proxy-manager
        environment:
            - PUID=${uid}
            - PGID=${gid}
            - TZ=${timezone}
        ports:
            - 81:81
            - 80:80
            - 443:443
        volumes:
            - ${config_path}/npm/data:/data
            - ${config_path}/npm/letsencrypt:/etc/letsencrypt

    # Plex config
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
            - PUID=${uid}
            - PGID=${gid}
            - TZ=${timezone}
            - VERSION=docker
            # - PLEX_CLAIM= #optional
        volumes:
            - ${config_path}/plex:/config
            - ${tv_path}:/tv
            - ${movies_path}:/movies
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped

    qbittorrent:
        image: dyonr/qbittorrentvpn
        container_name: qbittorrent
        environment:
            - PUID=${uid}
            - PGID=${gid}
            - VPN_ENABLED=yes
            - VPN_TYPE=openvpn
            - LAN_NETWORK=192.168.2.0/24
            - NAME_SERVERS=1.1.1.1,1.0.0.1
            - ENABLE_SSL=no
            - HEALTH_CHECK_HOST=one.one.one.one
        volumes:
            - ${config_path}/qbittorrent:/config
            - ${downloads_path}:/downloads
        ports:
            - 8080:8080
        privileged: true
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=${uid}
            - PGID=${gid}
            - TZ=${timezone}
        volumes:
            - ${config_path}/sonarr:/config
            - ${tv_path}:/tv
            - ${downloads_path}:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=${uid}
            - PGID=${gid}
            - TZ=${timezone}
        volumes:
            - ${config_path}/radarr:/config
            - ${movies_path}:/movies
            - ${downloads_path}:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=${uid}
            - PGID=${gid}
            - TZ=${timezone}
        volumes:
            - ${config_path}/prowlarr:/config
            - ${downloads_path}:/downloads
        ports:
            - 9696:9696
        restart: unless-stopped

    overseerr:
        image: lscr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
            - PUID=${uid}
            - PGID=${gid}
            - TZ=${timezone}
        volumes:
            - ${config_path}/overseerr:/config
        ports:
            - 5055:5055
        restart: unless-stopped

    # Auto updates docker images
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock