all:
  children:
    nas:
      hosts:
        # terramaster:
        #   ansible_host: 192.168.1.200
        #   ansible_user: truenas_admin
        #   ansible_become_password: "{{ vault_become_password }}"
        #   ansible_port: 9222
        #   ansible_connection: ssh
        #   ansible_python_interpreter: /usr/bin/python3
    laptop:
      hosts:
        potato:
          ansible_host: 192.168.1.201
          ansible_user: root
          ansible_port: 22
          ansible_python_interpreter: /run/current-system/sw/bin/python3.12
