pages:
  - name: Home
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    # hide-desktop-navigation: true
    columns:
      - size: full
        widgets:
          - type: search

          - type: monitor
            cache: 1m
            title: Servarr
            sites:
              - title: Plex
                url: https://plex.chaoshome.dev/web
                icon: di:plex
              - title: Overseerr
                url: https://overseerr.chaoshome.dev
                icon: di:overseerr
              - title: QBittorrent
                url: https://qbittorrent.chaoshome.dev
                icon: di:qbittorrent
              - title: Sonarr
                url: https://sonarr.chaoshome.dev
                icon: di:sonarr
              - title: Radarr
                url: https://radarr.chaoshome.dev
                icon: di:radarr
              - title: Bazarr
                url: https://bazarr.chaoshome.dev
                icon: di:bazarr

          - type: monitor
            cache: 1m
            title: Self-Hosted
            sites:
              - title: Immich
                url: https://immich.chaoshome.dev
                icon: di:immich
              - title: Minepanel
                url: https://minepanel.chaoshome.dev
                icon: di:minecraft

          - type: monitor
            cache: 1m
            title: OS
            sites:
              - title: TrueNAS
                url: https://nas.chaoshome.dev
                icon: di:truenas
              - title: Home Assistant
                url: http://home.chaoshome.dev
                icon: di:home-assistant

          - type: monitor
            cache: 1m
            title: Syncthing
            sites:
              - title: NAS Syncthing
                url: https://syncthing-truenas.chaoshome.dev
                icon: di:syncthing
              - title: Optiplex Syncthing
                url: https://syncthing-optiplex.chaoshome.dev
                icon: di:syncthing

          - type: videos
            # style: vertical-list
            # collapse-after: 6
            channels:
              - UCUBsjvdHcwZd3ztdY1Zadcw # Gem
              - UChFur_NwVSbUozOcF_F2kMg # Mumbo
              - UCR9Gcq0CMm6YgTzsDxAxjOQ # Grian
              - UCFKDEp9si4RmHFWJW1vYsMA # Etho

      - size: small
        widgets:
          - type: server-stats
            servers:
              - type: local
                name: Optiplex

          - type: server-stats
            servers:
              - type: remote
                name: NAS
                url: http://192.168.1.200:27973

          - type: weather
            location: Nantes, France
            units: metric # alternatively "imperial"
            hour-format: 24h # alternatively "24h"
            # Optionally hide the location from being displayed in the widget
            # hide-location: true

          - type: calendar
            first-day-of-week: monday
