server_ip: 192.168.1.200
server_user: truenas_admin
config_lan_network: 192.168.1.0/24

config_timezone: Etc/UTC
config_uid: 0
config_gid: 0

# ARR Stack

arr_root_path: "/home/{{ server_user }}/arr"
arr_config_path: "{{ arr_root_path }}/config"

arr_media_pool: /mnt/main-pool/media

arr_movies_path: "{{ arr_media_pool }}/movies"
arr_tv_path: "{{ arr_media_pool }}/tv-shows"
arr_download_path: "{{ arr_media_pool }}/torrents"
arr_transcode_path: "{{ arr_media_pool }}/transcode"

arr_homarr_key: "{{ vault_arr_homarr_key }}"

# Immich

imm_postgres_password: "{{ vault_imm_postgres_password }}"