---
- hosts: TerraMaster
  tasks:
    - name: copy Docker Compose files
      ansible.builtin.template:
        src: docker-compose.arr.yml.j2
        dest: "{{ arr_root_path }}/docker-compose.yml"

    - name: Restart services
      become: true
      ansible.builtin.shell:
        chdir: "{{ arr_root_path }}"
        cmd: docker compose up -d
