---
- hosts: TerraMaster
  tasks:
    - name: copy Docker Compose files
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "/home/{{ server_user }}/docker-compose.yml"

    - name: Restart services
      become: true
      ansible.builtin.shell:
        chdir: "/home/{{ server_user }}"
        cmd: docker compose up -d
